### ISSUE TITLE
TypeError when calling 'snake.more_menu();'

### ISSUE THREAD

**Issue by IanTerzo** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#101]
Uncaught TypeError: code.match(...) is null

Caused by [line 225 in custom.js](https://github.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/blob/b49a082fa02d07e7ba3820945903b52829636941/custom.js#L225)

For reference the custom options do appear in the menu but do not function when starting the game.
Tested on Firefox and Chrome

**Comment by Damianventur12** [comment]
yes. is a keyboard error

**Comment by Damianventur12** [comment]
thx yarmiplay
