### ISSUE TITLE
It's there, but it does not work

### ISSUE THREAD

**Issue by DeveloperJoshua14** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#104]
Hello! I am trying to use this mod, and all of the images and buttons will show up, but they will not do anything. 

This is the bookmark code I am using: 
javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();

**Comment by Damianventur12** [comment]
fixed
