### ISSUE TITLE
Half working 

### ISSUE THREAD

**Issue by windowmandav** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#105]
After importing bookmark the edited ui shows but after selecting a modded option it doesent change it stays as a normal google snake game

**Comment by Waffles1937** [comment]
ikr

**Comment by Damianventur12** [comment]
coy this ͌͋͊<3 `javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();`

**Comment by Damianventur12** [comment]
******  **  **  **  **b b ** **b fixed****

**Comment by Waffles1937** [comment]
Im sorry?

**Comment by Damianventur12** [comment]
is only a joke

**Comment by Waffles1937** [comment]
Please stop, then.
