### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by lwilson123** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#106]
ive tried multiple injection methods

**Comment by Damianventur12** [comment]
ok but what

**Comment by Damianventur12** [comment]
are you using another mod or maybe the thing fizhes said did this
plz not use multiple mods

**Comment by Damianventur12** [comment]
¨ plz other people close this thing ¨

**Comment by Damianventur12** [comment]
`javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();`

**Comment by Legendking32** [comment]
hi

**Comment by Damianventur12** [comment]
hi?

**Comment by Damianventur12** [comment]
O use my malito
mailto:damianventurasanchezgonzalez@gmail.com?subject=Question%3F
