### ISSUE TITLE
The speeds are not working

### ISSUE THREAD

**Issue by LaF9769** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#109]
I can use extra apples but none of the extra speeds are working, also, how do you paste the commands, into what? Please respond or fix code thanks :)

**Comment by hwatson381** [comment]
The dev fixed this today.

imo you should use the bookmark instead of pasting into console since it runs the same code anyway.

The console is the chrome dev console (ctrl+shift+j).

**Comment by trugam3rr** [comment]
new update!!1!1
