### ISSUE TITLE
I'm very confused on what exactly I need to do to install this on a Google Chrome laptop.

### ISSUE THREAD

**Issue by Wizard-34** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#11]
I'm very confused on what exactly I need to do to install this on a Google Chrome laptop. Please give instructions.

**Comment by Deconder** [comment]
Yeah same

**Comment by Yarmiplay** [comment]
There's nothing to install, you only need to download and import the bookmark. Then go the actual game in the browser, launch it and click on the bookmark.

If you are unsure still about the process, we can help you on the discord here: https://discord.gg/9UQkENPS
