### ISSUE TITLE
I know how to make it work

### ISSUE THREAD

**Issue by kristheamazing2** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#110]
First you need to download the hack then go to chrome://bookmarks, and go to the three buttons at the top and press import bookmarks. Then it comes up with your files, you have to find where it says MoreMenu(1)html, you click on that and press on the three dots on the bookmark that says imported. Then you rename to Snake Game Hacks so you can remember, then go into snake game and go to the three dots press bookmarks then press Snake Game Hacks and it should come up with More Menu Stuff click on that and check your game.

**Comment by Yarmiplay** [comment]
Not an issue.
