### ISSUE TITLE
Can You Make A GUN Mod

### ISSUE THREAD

**Issue by BannanaPants** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#111]
I really like your mods but there's no gun mod so can you make one? P.S. When are the snakezilla and switcheraroo mods coming out?

**Comment by Yarmiplay** [comment]
Please detail what gun mod is supposed to be
The others are up to Llama and I think would be in a different repo

**Comment by BannanaPants** [comment]
I mean like it adds  a gun/s next to the snake and there could be enemy snakes you shoot at or something.

**Comment by BannanaPants** [comment]
Also who is the Llama your talking about?

**Comment by Yarmiplay** [comment]
idk about that whole gun idea, Llama is the person that made snakezilla and switcheroo mods in this video https://www.youtube.com/watch?v=7xiLUZeTm-k
