### ISSUE TITLE
Error when loading in Menu

### ISSUE THREAD

**Issue by tripleaaabattery** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#113]
Whenever I load in the menu, I get an error in the console saying "Uncaught TypeError: Cannot read properties of null (reading '0') at req.onload (eval at req.onload (search:1:166), <anonymous>:232:93)" and the menu would not load anything other than the settings from the base game.

**Comment by Deibix** [comment]
It is true, the mod is useless, the mod menu appears but its functions do not work.

**Comment by hwatson381** [comment]
You need to get https://github.com/DarkSnakeGang/GoogleSnakeModLoader/ instead. This includes More Menu Mod.
