### ISSUE TITLE
Mods don't work

### ISSUE THREAD

**Issue by Deibix** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#114]
I really like playing Google Snake with mods, but today they stopped working. The mod menu appears but does not work.

**Comment by hwatson381** [comment]
yeah this happens sometimes if the code for Google Snake changes. I'll pass this on to the mod creator, so hopefully they can fix soon.

**Comment by hwatson381** [comment]
I think it was a fairly major change to the google snake code.
