### ISSUE TITLE
[GUIDE] Running an old version of the mod on archive.org

### ISSUE THREAD

**Issue by hwatson381** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#116]
Currently the mod is broken due to a major change in google snake code.

In the meantime, this is a workaround for running an old version of the mod on an old version of snake.

https://web.archive.org/web/20221222083337/https://www.google.com/fbx?fbx=snake_arcade

Go to that page

When on that page, you then open javascript console (ctrl+shift+j) and paste in the code from this webpage and hit enter https://github.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/blob/b72964f49c4863a69993566d7eab985287be784b/custom.js

Also paste in this command and hit enter
window.snake.more_menu();

**Comment by hoseinking36** [comment]
it doesnt work there either

**Comment by hwatson381** [comment]
Workaround isn't needed anymore.

You can get this instead https://github.com/DarkSnakeGang/GoogleSnakeModLoader/ instead. This includes More Menu Mod.
