### ISSUE TITLE
Error when running on console

### ISSUE THREAD

**Issue by Box-OS** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#118]
The UI is there but it does nothing. Here's the error:
<img width="780" alt="Screenshot 2023-02-16 at 11 11 11 AM" src="https://user-images.githubusercontent.com/85126535/219423660-069d1f17-1779-4e47-90d7-b96afe8db352.png">

**Comment by hwatson381** [comment]
You need to get https://github.com/DarkSnakeGang/GoogleSnakeModLoader/ instead. This includes More Menu Mod.
