### ISSUE TITLE
I can't use this during school I get an error message seen down below

### ISSUE THREAD

**Issue by Dark-Snake-Gang** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#12]
When I am at home the mods work fine, but at school Custom Menu and Dark Mode are blocked, the error message goes something like this, 
Uncaught Error CONNECTION FAILED...
Can someone post a line of code that I can paste into the console 
Thanks

**Comment by Yarmiplay** [comment]
The code is open source here https://github.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/blob/main/custom.js
Your school network is probably blocking the connections to the files, use a VPN.

**Comment by Dark-Snake-Gang** [comment]
All VPN websites are blocked but on Monday I'll try
