### ISSUE TITLE
Please make it work with no extension

### ISSUE THREAD

**Issue by lgshue** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#124]
my school has tampermonkey blocked :/

**Comment by hwatson381** [comment]
we have googlesnakemods.com now for playing without extensions

**Comment by lgshue** [comment]
sadly i still cant play it as its blocked by my school :( thanks for trying though

**Comment by hwatson381** [comment]
> sadly i still cant play it as its blocked by my school :( thanks for trying though

Oh damn. I didn't even realize that was a possibility. The site has only been out for a week or so. Do you think they could be blocking url's that contain googlesnake anywhere in them? hmmm or maybe they block the IP address as it's hosting on github pages?

**Comment by lgshue** [comment]
![Screenshot 2024-01-10 7 48 20 AM](https://github.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/assets/149423753/80aaef7f-ba84-49a8-aeba-2dd37270d677)

**Comment by lgshue** [comment]
idk

**Comment by hwatson381** [comment]
Thanks for the screenshot, I looked up Linewize and seems like it's quite a widely used blocker, but idk how to get around it (other than using a proxy I suppose). Does clicking on "see why it's blocked" do anything?

**Comment by lgshue** [comment]
no
