### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by Deconder** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#14]
What do they mean when they say copy the code into the console what is the console please help

**Comment by sagi312** [comment]
For Google Chrome: When you're in-game, right click and choose inspect. A window will pop up on the right, choose "console" in the upper menu, and then paste the code and press enter. After that type "window.snake.more_menu();" and the menu will update. Have fun!

**Comment by Deconder** [comment]
Thank you but I already figured it out and its just easier to put /releases behind the link then download the bookmark

**Comment by xXMaxLayXx** [comment]
somehow it didn't work on my computer
<img width="829" alt="Screenshot 2021-11-15 134234" src="https://user-images.githubusercontent.com/94403874/141851072-ba5f7f10-d3a7-4f38-a540-cff2ae44cf3c.png">
 

I tried to do bookmarks it, but t didn't work.

**Comment by Yarmiplay** [comment]
Join here for quick help on this stuff https://discord.gg/9UQkENPS
