### ISSUE TITLE
I can't see the logos of each of the option in settings

### ISSUE THREAD

**Issue by BroyoProductions** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#15]
I can't see the logos of each of the option in settings other then the options that are normal and I can see 2 speed ones and 1 food one.

**Comment by Yarmiplay** [comment]
Are you using on a network that blocks connections, such as a school network or a school PC? Are you using the latest version?

**Comment by BroyoProductions** [comment]
> Are you using on a network that blocks connections, such as a school network or a school PC? Are you using the latest version?

No for first and yes for second

**Comment by hwatson381** [comment]
Check to see if all these links work (They are images that the mod uses)
https://i.postimg.cc/FHxxLK4m/micro-1.png
https://cdn.discordapp.com/attachments/723093815786864661/894286619530653726/unknown.png
https://thumbs.dreamstime.com/z/number-isolated-white-background-110844960.jpg
https://www.funimada.com/assets/images/cards/big/40th-birthday-36.gif
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Bundesstra%C3%9Fe_87_number.svg/1200px-Bundesstra%C3%9Fe_87_number.svg.png

**Comment by BroyoProductions** [comment]
> Check to see if all these link work for you (They are images that the mod uses)
> https://i.postimg.cc/FHxxLK4m/micro-1.png
> https://cdn.discordapp.com/attachments/723093815786864661/894286619530653726/unknown.png
> https://thumbs.dreamstime.com/z/number-isolated-white-background-110844960.jpg
> https://www.funimada.com/assets/images/cards/big/40th-birthday-36.gif
> https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Bundesstra%C3%9Fe_87_number.svg/1200px-Bundesstra%C3%9Fe_87_number.svg.png

I can see them there but not in game and I’m not on my computer rn

**Comment by TheDItto** [comment]
i think it is Chans i see them and i use school computer and wifi

**Comment by BrightyLighty** [comment]
This issue is fixed for some people in a change I just proposed, but it is technically impossible to permanently fix for everyone because it's typically caused by school wifis blocking stuff. Still, using a consistent image host for everything reduces the chances of pure and absolute failure

**Comment by Yarmiplay** [comment]
@fizhes how about moving the hosting of images to the github itself?

**Comment by Mason979** [comment]
I cant even use the speed mods or see any pictures of them also including the apple pictures except for the big tree and the map pictures but it worked for my brother who is in my house and got it 1 day apart from me and everything works including the pictures.

**Comment by BrightyLighty** [comment]
> @fizhes how about moving the hosting of images to the github itself?

That would make much more sense, actually. Why did nobody think of that?

> I cant even use the speed mods or see any pictures of them also including the apple pictures except for the big tree and the map pictures but it worked for my brother who is in my house and got it 1 day apart from me and everything works including the pictures.

Can you send a screenshot of the issue?

**Comment by hecker1234567890** [comment]
the thing should work if you download the file or have the javascript, it will update by it self, well that wat happens to me

**Comment by hecker1234567890** [comment]
you also should press or use the javascript once

**Comment by Yarmiplay** [comment]
This was changed, good luck
