### ISSUE TITLE
Update fetching method to be cleaner

### ISSUE THREAD

**Issue by sylvxa** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#18]
Instead of using XML requests, use fetch() as it is more modern and generally cleaner. The code required to do so is below:

`javascript:fetch("https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js").then((response) => response.text()).then((responseText) => {eval(responseText)});
`

**Comment by Yarmiplay** [comment]
@hwatson381 what do you think about this?

**Comment by rcaahsiemy** [comment]
v

**Comment by TruGam3rr** [comment]
not working it just makes the game break

**Comment by TruGam3rr** [comment]
it used to work but not anymore

**Comment by Yarmiplay** [comment]
try now @TruGam3rr I think it's fixed

**Comment by ruby-dev-1** [comment]
g

**Comment by ruby-dev-1** [comment]
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g

**Comment by ruby-dev-1** [comment]
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g

**Comment by ruby-dev-1** [comment]
> Instead of using XML requests, use fetch() as it is more modern and generally cleaner. The code required to do so is below:
> 
> `javascript:fetch("https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js").then((response) => response.text()).then((responseText) => {eval(responseText)}); `

n

**Comment by Damianventur12** [comment]
Fixed
`javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();`

**Comment by Damianventur12** [comment]
¿I can collaborate for the html codes?

**Comment by trugam3rr** [comment]
> req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();

works, nice job

**Comment by hwatson381** [comment]
hmm interesting. Custom speeds seem to work on the standalone snake https://www.google.com/fbx?fbx=snake_arcade but not on search snake.

**Comment by hwatson381** [comment]
> it works, nice job. only thing that doesnt work are the custom speeds.

btw the dev fixed this today
