### ISSUE TITLE
Bookmark Bug

### ISSUE THREAD

**Issue by Flowersepic** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#19]
So basically when I  click the book mark it, it just takes me to a source code that says, Bookmarks Bookmarks Bar More Menu. How do I fix this?

**Comment by hwatson381** [comment]
When you are on that page, you should drag the "More Menu Stuff" link to your bookmark bar (in chrome, but I assume it's similar for other browsers).

**Comment by Flowersepic** [comment]
I did that but it just takes me to a website.

**Comment by youareaclown-boop** [comment]
> When you are on that page, you should drag the "More Menu Stuff" link to your bookmark bar (in chrome, but I assume it's similar for other browsers).

too bad when you drag it bookmark bar disappears.

**Comment by Yarmiplay** [comment]
@hwatson381 only works on chrome, opera and firefox don't have that feature sadly.
@Flowersepic right click to download the file, than go to settings and import them from there.
