### ISSUE TITLE
it dont work :(

### ISSUE THREAD

**Issue by defineperson** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#2]
`window.snake.burger({
  dark: true
});
undefined
VM75:56 Uncaught TypeError: Cannot read properties of null (reading '0')
    at processSnakeCode (<anonymous>:56:4)
    at XMLHttpRequest.req.onload (<anonymous>:49:3)`

**Comment by Yarmiplay** [comment]
join the discord https://discord.gg/PZbrXF2P and go to #snake-modding we might be able to help your particular issue there
