### ISSUE TITLE
Idk where the console is

### ISSUE THREAD

**Issue by DaNewKXD** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#21]
I don't know where the console is.

**Comment by danlmao737** [comment]
Just use it as a bookmark, right click . Save link as and download MoreMenu.HTML. Right click on the book mark bar and click "Import." Click on the file you downloaded before and you have it, its in the "Imported" folder. Just click on it when your playing snake and it will load.

**Comment by DaNewKXD** [comment]
thanks, your great.
