### ISSUE TITLE
Geting Google “Unusual Traffic” Error 

### ISSUE THREAD

**Issue by pJsILy** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#22]
When I have the mod download I get an “Unusual Traffic” Error when I search something up, and it kind of gets annoying plz fix it. tysm :D !

**Comment by hwatson381** [comment]
Using this link should be a bit better https://www.google.com/fbx?fbx=snake_arcade

**Comment by hwatson381** [comment]
Should be fixed now.
