### ISSUE TITLE
Google "Unusual Traffic" Error

### ISSUE THREAD

**Issue by Legonix** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#24]
Hey @fizhes every once in a while I keep getting an error that says: "Unusual traffic from your computer network” or “Our systems have detected unusual traffic from your computer network".  I was wondering if there was a way that you could fix this, and I hope this file isn't malware...

**Comment by Dark-Snake-Gang** [comment]
Same here...the captcha is annoying and it happens most of the time during the direct search of "snake" it stops occuring after awhile though

**Comment by hwatson381** [comment]
It's not malware. It is something that should be fixed though.

If you want to avoid it then stick to using:
https://www.google.com/fbx?fbx=snake_arcade

**Comment by hwatson381** [comment]
Should be fixed now.
