### ISSUE TITLE
idk smths wrong 

### ISSUE THREAD

**Issue by LOLgamts** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#26]
in the video im watching as a tutorial (https://www.youtube.com/watch?v=PlP7etdPaNc) there is a "moremenu.html" file that he clicks that isnt showing up for me, pls tell me why

**Comment by jose-py** [comment]
It's right here https://github.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/releases/tag/Permanent
You have to click on the releases tab

**Comment by Yarmiplay** [comment]
If you still didn't manage, ask for support here: https://discord.gg/Bm856mCH
