### ISSUE TITLE
it won't let me see or download the mod

### ISSUE THREAD

**Issue by EAGLESRULE2021** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#29]
It says Enable The Mod and There Is No Mod There To Download. PLEASE FIX THIS!!!   😡
Fix It Because I Want To Try It. I Have A Boring One Already But It's BORING

**Comment by Yarmiplay** [comment]
What are you talking about? Anyways, ask for support here: https://discord.gg/Bm856mCH

**Comment by EAGLESRULE2021** [comment]
It Says Enable The Mod. Where Do I Find It? Pls Help.

**Comment by EAGLESRULE2021** [comment]
Also Could You Tell Me What To Do To Activate The Mod?
