### ISSUE TITLE
Feature request: No Apples

### ISSUE THREAD

**Issue by Cortex128** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#30]
You have lots of options for more apples than normal. But what about no apples at all? It is completely impossible to collect a single apple. I think this would be an invaluable addition to the mod

**Comment by Heeper** [comment]
how can i use the mode

**Comment by Yarmiplay** [comment]
Invaluable as in has no value?
What would be the point of 0 apples, all you could do there is die/reset.

**Comment by Voidacular** [comment]
I can add this, but there is no reason for this addition.
