### ISSUE TITLE
How do you make a snake mod?

### ISSUE THREAD

**Issue by BannanaPants** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#31]
Dear fizhes,

Hey, I'm a beginner coder and I'm wondering how you make a snake mod and how you code with GitHub. Please respond.

From,
BananaPants

**Comment by Voidacular** [comment]
The snake mod is made fully in JavaScript, and so to find elements, you can use Inspect Element. GitHub has two ways to upload code. One way, is by using the website editor. A secondary way is by using `git` in the command line.

**Comment by Voidacular** [comment]
`document.querySelector('#x').appendChild(img);`
is the section its found in. Replace x with speed, count, or more.

**Comment by Voidacular** [comment]
What you can do, is look at the code, and make your own modifications.

**Comment by Michael97** [comment]
Is it possible to add your own food images?

**Comment by BannanaPants** [comment]
How do you add code  to a project?

**Comment by Yarmiplay** [comment]
Go search for tutorials on YouTube.
