### ISSUE TITLE
can someone help me 

### ISSUE THREAD

**Issue by ilikecode214** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#35]
can someone comment the code to add as a bookmark myself but the dark mode.

like this but for dark mode{

`javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();`}

@Yarmiplay can you give me the code to add it as a bookmark myself for dark mode
or tell me where to find it

**Comment by ilikecode214** [comment]
@Yarmiplay  can you give me the code to add it as a bookmark myself for dark mode 
or tell me where to find it

**Comment by Yarmiplay** [comment]
https://github.com/DarkSnakeGang/GoogleSnakeDarkMode/releases/tag/Permanent
