### ISSUE TITLE
wont work for me

### ISSUE THREAD

**Issue by ilikecode214** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#5]
it wont save to my files on my school chromebook

**Comment by HenryBass** [comment]
If the chromebook won't let you download, try copying the JS file into inspect element. If inspect is blocked, try just creating a .js file with the code. After that, don't know how to help.

**Comment by Yarmiplay** [comment]
if you can create a file it's possible to manually copy the code and make your own bookmark, although it's a bit more work

**Comment by ilikecode214** [comment]
> if you can create a file it's possible to manually copy the code and make your own bookmark, although it's a bit more work

how do i make it a bookmark with the code??

**Comment by Yarmiplay** [comment]
Right click -> Add Bookmark/Add Site (depends on browser)
and paste this in:
```
javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();
```

**Comment by ilikecode214** [comment]
> Right click -> Add Bookmark/Add Site (depends on browser) and paste this in:
> 
> ```
> javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();
> ```

what broswer??

**Comment by Yarmiplay** [comment]
Closing since no reply in 5 days.

**Comment by boofffffffffffffffffff** [comment]
I tried creating a bookmark in a new folder but it didn't work. Is it because I'm on a school chromebook?

**Comment by boofffffffffffffffffff** [comment]
I made a new folder then a new page in it.

**Comment by Unknown6858** [comment]
how do you do that?

> I made a new folder then a new page in it.
