### ISSUE TITLE
I just begun onto github, can I get any help making my own mod for snake?

### ISSUE THREAD

**Issue by Ponkers8149** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#51]
Also no I am not one of those 5-year-olds who are spamming, "I like ya cut g." I just want to learn how to code so I can help others as the one who helps me would be passed down with information. 

-Ponkers8149

**Comment by johanmom** [comment]
i need help ponker

**Comment by Yarmiplay** [comment]
Good luck but that's not and issue with the code here. https://discord.gg/P58danvb
