### ISSUE TITLE
SnakeGameMod

### ISSUE THREAD

**Issue by wdsTikTok** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#63]
When using the mod I can't use the added on maps, I can only use the original ones

**Comment by Yarmiplay** [comment]
different sizes don't work? please show your browser console to see what error comes up, or a video of it happening

**Comment by wdsTikTok** [comment]
I think that the problem is that whenever I changed the background I cant play the attached maps. So I guess I'll just not play with a background

**Comment by Yarmiplay** [comment]
Yeah it's because the new update just came out it seems

**Comment by cvrsedW** [comment]
> Yeah it's because the new update just came out it seems

do you have plans to fix it or no

**Comment by Yarmiplay** [comment]
FIXED!
