### ISSUE TITLE
fruit amount, map size, and speed dosent work anymore

### ISSUE THREAD

**Issue by ruby-dev-1** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#68]
the fruit amounts dont work anymore, rather the entire mod menu dosent work, trying to adjust the fruit always gives you 3 fruit. the speed will be set to turtle speed. and the background size will reset to medium, i just had this issue today

**Comment by GhostIsBeHere** [comment]
I am having this issue as well

**Comment by Randum28** [comment]
I am also having this issue, my theory is google released an update to add map styles and accidentally ended up disabling certain mods.

**Comment by Yarmiplay** [comment]
google made an update that breaks this mod for the moment
since the account that opened this issue also spammed us, I'll close this one as well.
