### ISSUE TITLE
fuck you niggers

### ISSUE THREAD

**Issue by ruby-dev-1** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#69]
░░░░░░░░████░░░░░
░░░░░░░██░████░░░
░░░░░░░█░░█░░██░░
░░░░░░░█░░░░░░█░░
░░░░░░░█████████░
░░░░░░░█░░░░░░░█░
░░░░░░░█░░░░░░░██
░░░░░░░█░░░░░░░░█
░░░░░███░░░░░░░░█
░█████░█░░░░░░░░█
░█░░░░░█░░░░░░░█░
░█████░█░░░░░░░█░
░██░░███░░░░░░██░
░█░░░░░█░░░░░░█░░
░█░░░░░░░░░░░░█░░
░█░░░░░░░░░░░░█░░
░██░░░░░░░░░░░█░░
░░███░░░░░░░░░█░░
░░░░███████████░░

**Comment by Yarmiplay** [comment]
reported to github support
