### ISSUE TITLE
The sprites work but the mods themselves dont

### ISSUE THREAD

**Issue by MrGerbil** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#80]
I got it and followed the steps and everything seem to work fine however when I go to play and use one of the new "modded" features it resorts back to a default state when I go to play, for example if I do any of the new added speed options other then the normal unchanged speed when I start the snake will only go the normal speed. This is true as well for if I try to change the number of apples ; when I try to use a lot of a modded option the game defaults back to only having 3 apples. I do see a new vanilla option so my only guess (as i don't code ) is that the new update is interfering with the mod.

**Comment by Yarmiplay** [comment]
FIXED!
