### ISSUE TITLE
Mod was error.

### ISSUE THREAD

**Issue by OldJERN8322** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#82]
Also a this not working a error.

https://user-images.githubusercontent.com/99561059/167942542-926d8c68-da40-4f51-a1d4-5459cc1db7de.mp4

look a this screenshot.

![image](https://user-images.githubusercontent.com/99561059/167942610-2d8c36a9-40fe-4097-bea4-c0a9575b4da8.png)

Also a update in version.

**Comment by Yarmiplay** [comment]
FIXED!
