### ISSUE TITLE
Custom sizes don't work

### ISSUE THREAD

**Issue by orrinpants** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#85]
Title

**Comment by orrinpants** [comment]
That's exactly how it's working for me

**Comment by Yarmiplay** [comment]
![image](https://user-images.githubusercontent.com/6286286/168746453-c21682e8-3b7a-439c-abac-303451712345.png)
they work for me though...

**Comment by Yarmiplay** [comment]
alright seems like a new version is rolling out that is indeed breaking it

**Comment by Logan20063** [comment]
Yeah I got it on 2 devices within the past 2-3 days so it might be a relatively new update

**Comment by Yarmiplay** [comment]
fixed
