### ISSUE TITLE
it wont let me use anything on it

### ISSUE THREAD

**Issue by gavinb77** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#9]
heres a video of what i mean  

https://user-images.githubusercontent.com/94120205/141306562-e1fd9ffe-9de0-451e-96b3-80c59dfb0f54.mp4

**Comment by BroyoProductions** [comment]
mine does the same idk how to fix it

**Comment by Yarmiplay** [comment]
Is this the latest version?

**Comment by Yarmiplay** [comment]
Are you using on a network that blocks connections, such as a school network or a school PC?

**Comment by gavinb77** [comment]
yes it must be that i will use my hotspot now
