### ISSUE TITLE
mod not working ._.

### ISSUE THREAD

**Issue by ImPalyYT** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#94]
sprites work but not the mod i tried on brave browser i got error and i tried it on chrome error again

![Screenshot (47)](https://user-images.githubusercontent.com/97025017/173005286-9cf3781f-598c-4b3d-ac9c-b36c6e6e0b1a.png)

**Comment by Erisfiregamer1** [comment]
What's not working? It looks like it loaded fine, did you even test it?

**Comment by Yarmiplay** [comment]
there are 2 other issues about the same topic already open, closing
we know about this already, thanks
