### ISSUE TITLE
the apples dont work

### ISSUE THREAD

**Issue by RyanNotAnimates** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#99]

**Comment by HeadhunterAli** [comment]
vouch

**Comment by Damianventur12** [comment]
only put the js code. and put it in the console. Work Now. You these in the HTML Release
Thanks For The Help!

**Comment by Damianventur12** [comment]
javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js'); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();
